### ISSUE TITLE
Add more @media test case

### ISSUE THREAD

**Issue by yisibl** [ben-eb/perfectionist#1]
Like this:

```css
@media
  only screen and (-o-min-device-pixel-ratio: 2/1),
  only screen and (min--moz-device-pixel-ratio: 2),
  only screen and (-moz-min-device-pixel-ratio: 2),
  only screen and (-webkit-min-device-pixel-ratio: 2),
  only screen and (min-resolution: 192dpi),
  only screen and (min-resolution: 2dppx) {
  .selector {
    background-size: 30px 50px;
  }
}


@media only screen and (max-width: 600px) {
  @media only screen (min-width: 200px) {
    .foo {
      display: block;
    }
  }
}
```
