### ISSUE TITLE
Removing comments

### ISSUE THREAD

**Issue by Mottie** [ben-eb/perfectionist#11]
Sorry to be a pain, because this is probably an edge case... but we do have [this situation](https://github.com/StylishThemes/GitHub-Dark/blob/master/github-dark.css#L1776-L1783).

I tried to provide a reduced case and found that if there are more than 3 selectors in a row followed by at least 3 comments, the comments get removed.  Then I found some other odd behavior... so starting with the following css and using default settings:

```css
 /* 2 selectors + 3 comments + 3 selectors */
 .selectorA, .selectorB,
 /* comment 1 */
 /* comment 2 */
 /* comment 3 */
 .selectorD, .selectorE, .selectorF {
   color: white;
 }
 /* 3 selectors + 2 comments + 3 selectors */
 .selectorA, .selectorB, .selectorC,
 /* comment 1 */
 /* comment 2 */
 .selectorD, .selectorE, .selectorF {
   color: white;
 }
 /* 3 selectors + 3 comments + 3 selectors */
 .selectorA, .selectorB, .selectorC,
 /* comment 1 */
 /* comment 2 */
 /* comment 3 */
 .selectorD, .selectorE, .selectorF {
   color: white;
 }
 /* 4 selectors + 2 comments + 3 selectors */
 .selectorA, .selectorB, .selectorC, .selectorX,
 /* comment 1 */
 /* comment 2 */
 .selectorD, .selectorE, .selectorF {
   color: white;
 }
 /* 4 selectors + 1 comment + 3 selectors */
 .selectorA, .selectorB, .selectorC, .selectorX,
 /* comment 1 */
 .selectorD, .selectorE, .selectorF {
   color: white;
 }
 /* 4 selectors + 1 comment + 2 selectors */
 .selectorA, .selectorB, .selectorC, .selectorX,
 /* comment 1 */
 .selectorD, .selectorE {
   color: white;
 }
```

This is the result:

```css
/* 2 selectors + 3 comments + 3 selectors */

.selectorA, .selectorB,
 /* comment 1 */
 /* comment 2 */
 /* comment 3 */
 .selectorD, .selectorE, .selectorF {
    color: white;
}

/* 3 selectors + 2 comments + 3 selectors */

.selectorA, .selectorB, .selectorC,
 /* comment 1 */
 /* comment 2 */
 .selectorD, .selectorE, .selectorF {
    color: white;
}

/* 3 selectors + 3 comments + 3 selectors */

.selectorA, .selectorB, .selectorC, .selectorD, .selectorE, .selectorF {
    color: white;
}

/* 4 selectors + 2 comments + 3 selectors */

.selectorA, .selectorB, .selectorC, .selectorX, .selectorD, .selectorE,
.selectorF {
    color: white;
}

/* 4 selectors + 1 comment + 3 selectors */

.selectorA, .selectorB, .selectorC, .selectorX, .selectorD, .selectorE,
.selectorF {
    color: white;
}

/* 4 selectors + 1 comment + 2 selectors */

.selectorA, .selectorB, .selectorC, .selectorX,
 /* comment 1 */
 .selectorD, .selectorE {
    color: white;
}
```

The last case is an especially odd one... I think it might have something to do with the `maxSelectorLength` setting.

**Comment by ben-eb** [comment]
I'll see if I can get to this tomorrow. :+1:

**Comment by ben-eb** [comment]
I can stop perfectionist removing the comments, however the formatting is kind of wonky on this, for example:

```css
/* 3 selectors + 3 comments + 3 selectors */

.selectorA, .selectorB, .selectorC,
/* comment 1 */
 /* comment 2 */
 /* comment 3 */
 .selectorD, .selectorE,
.selectorF {
    color: white;
}
```

But I'm not sure if I want to start parsing selector comments for newlines, especially as you say it's kind of an edge case as it is. I would appreciate any help regarding this if it's important to people. :+1:
