### ISSUE TITLE
Support CSS apply rules

### ISSUE THREAD

**Issue by ben-eb** [ben-eb/perfectionist#12]
```css
:root {
  --toolbar-theme: {
    background-color: hsl(120, 70%, 95%);
    border-radius: 4px;
    border: 1px solid var(--theme-color late);
  };
  --toolbar-title-theme: {
    color: green;
  };
}
```
