### ISSUE TITLE
Support comma segmentation split

### ISSUE THREAD

**Issue by yisibl** [ben-eb/perfectionist#16]
Input:

```css
.foo {
  color: rgba(68,120,10,.5);
  background-image: linear-gradient(to top right,red,white,blue);
}
```

Output:

```css
.foo {
  color: rgba(68, 120, 10, .5);
  background-image: linear-gradient(to top right, red, white, blue);
}
```
