### ISSUE TITLE
Remove a single comment

### ISSUE THREAD

**Issue by yisibl** [ben-eb/perfectionist#18]
Input:

```scss
.bar {
  // single comment
  transform: scale(0);
}
```

If we use `Compact` or `Compressed `

Output:

```scss
.bar {// single comment transform: scale(0); }
```

We must be remove `// single comment `,

or transform to

`Compact`
```scss
.bar { // single comment
transform: scale(0) }
```

`Compressed`
```scss
.bar{// single comment
transform:scale(0)}
```

or just transform to `/* single comment */ `
