### ISSUE TITLE
Format brackets "()"

### ISSUE THREAD

**Issue by yisibl** [ben-eb/perfectionist#19]
Input

```scss
@media (  min-width:        30.2em   ) {
  .foo {
    color: rgba(   90,200,12,.5   );
  }
}
```

Output:

```scss
@media (min-width: 30.2em) {
  .foo {
    color: rgba(90, 200, 12, .5);
  }
}
```
