### ISSUE TITLE
Support for rule separation

### ISSUE THREAD

**Issue by itsjustmath** [ben-eb/perfectionist#26]
[Separate rules by new lines](https://google.github.io/styleguide/htmlcssguide.xml?showone=Rule_Separation#Rule_Separation)
 > Always put a blank line (two line breaks) between rules.

```css
html {
  background: #fff;
}

body {
  margin: auto;
  width: 50%;
}
```
