### ISSUE TITLE
Add newline (or 2) before opening comment

### ISSUE THREAD

**Issue by kwoodfriend** [ben-eb/perfectionist#4]
Take a look at the following minimized CSS sample, and perfectionist output. As you can see, the last comment is snug up against the closing bracket of the previous block. 

Also, it's hard to spot at first, but the first comment is actually 2 comments, and could benefit from new lines added between them. Probably harder to implement, though. I'm not that familiar with PostCSS, not sure what functionality it has for comments.

Minimized CSS:
```css
/*! normalize.css v3.0.2 | MIT License | git.io/normalize *//**
 * 1. Set default font family to sans-serif.
 * 2. Prevent iOS text size adjust after orientation change, without disabling
 *    user zoom.
 */html {font-family: sans-serif;-ms-text-size-adjust: 100%;-webkit-text-size-adjust: 100%;}/**
 * Remove default margin.
 */body {margin: 0;}
```

Output:
```css
 /*! normalize.css v3.0.2 | MIT License | git.io/normalize *//**
  * 1. Set default font family to sans-serif.
  * 2. Prevent iOS text size adjust after orientation change, without disabling
  *    user zoom.
  */

 html {
     font-family: sans-serif;
         -ms-text-size-adjust: 100%;
     -webkit-text-size-adjust: 100%;
 }/**
  * Remove default margin.
  */

 body {
     margin: 0;
 }
```

Thanks again!
