### ISSUE TITLE
Base 64 encoded images

### ISSUE THREAD

**Issue by Mottie** [ben-eb/perfectionist#43]
When a css definition includes a hex color and a base 64 encoded image, the image is converted to all lower case. For example, given this css:

```css
.arrows {
  background: #181818 url("data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABAAAAAUCAQAAAAua3X8AAAARklEQVR4AWNABWcazjQg8zGl/wNhA15piBL80gglmNKYSjClMZUgpDGVwKXxKBl4QNiRBLxJIKAIBzXhyCIc3YQTDMEkBwBplPJRxEMa4wAAAABJRU5ErkJggg==");
}
```

the `applyTransformFeatures` function will determine that the following `rule.value` is a hex color:

```
#181818 url("data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABAAAAAUCAQAAAAua3X8AAAARklEQVR4AWNABWcazjQg8zGl/wNhA15piBL80gglmNKYSjClMZUgpDGVwKXxKBl4QNiRBLxJIKAIBzXhyCIc3YQTDMEkBwBplPJRxEMa4wAAAABJRU5ErkJggg==")
```

From looking at the code, no matter the setting of the `colorCase` option, this image URI will be destroyed by applying a ` .toLowerCase()` function at [line 303](https://github.com/ben-eb/perfectionist/blob/master/src/index.js#L303) or `.toUpperCase()` function at [line 305](https://github.com/ben-eb/perfectionist/blob/master/src/index.js#L305) of the `index.js` file.

Restoring the start and end anchors of the `isHexColor.js` match regex (removed in [pr #36](https://github.com/ben-eb/perfectionist/commit/75a60757d1c61c1cff93534efa100426c1343e75#diff-57cc2e57a85b291804f240cb5af098a0)), would fix this issue, but I didn't test if anything else would break.

```js
exports.default = function (color) {
  return color.match(/^#([A-Fa-f0-9]{6}|[A-Fa-f0-9]{3})$/) !== null;
};
```
