### ISSUE TITLE
Add `maxValueLength`

### ISSUE THREAD

**Issue by Justineo** [ben-eb/perfectionist#5]
Like `maxSelectorLength`, to split value over multiple lines only if its length exceeds the specified limit.

I got results seemed weird now:

```css
.x {
    transition-duration: 0.5s,
                         2s;
}
```

The following format seems prettier:

```css
.x {
    transition-duration: 0.5s, 2s;
}
```
