### ISSUE TITLE
Trim or add leading zeroes?

### ISSUE THREAD

**Issue by keithjgrant** [ben-eb/perfectionist#75]
How should we deal with leading zeros on decimal values? Trim them, add them, or leave as authored?

```css
.foo {
  /* trim */
  padding: .2em;
}

.bar {
  /* add them */
  padding: 0.2em;
}
```

Poll on Twitter to get a feel for public opinion: https://twitter.com/ben_eb/status/862994803759382528
