### ISSUE TITLE
Aligning vendor prefixes

### ISSUE THREAD

**Issue by keithjgrant** [ben-eb/perfectionist#79]
This is another option that should probably get cut. Which way to align vendor prefixes?

```css
.dont-align {
    -webkit-user-select: none;
    -moz-user-select: none;
    -ms-user-select: none;
    user-select: none;
}

.align {
    -webkit-user-select: none;
       -moz-user-select: none;
        -ms-user-select: none;
            user-select: none;
}
```

**Comment by keithjgrant** [comment]
I'm in favor of not aligning (i.e. indenting normally). This avoids weird-looking "hanging" declarations beneath:

```css
.wonky {
    -webkit-user-select: none;
       -moz-user-select: none;
        -ms-user-select: none;
            user-select: none;
    color: green;
}
```

As @benfrain [pointed out](https://gist.github.com/keithjgrant/d35fc6a72253c91a60c6c6c15f5ce6ff#gistcomment-2092655), leave it to AutoPrefixer.
