### ISSUE TITLE
Comments being removed

### ISSUE THREAD

**Issue by Mottie** [ben-eb/perfectionist#8]
We use our styles at userstyles.org, so some css definitions have [placeholder comments](https://userstyles.org/help/coding#help-style-settings-placeholders) within the definition (see "placeholder" in the example below) which get replaced with user set choices:

```css
.selector {
  /* comment 1 */
  color: /*[[placeholder]]*/ white;
  /* comment 2 */
}
```

With default settings, the result removes the essential placeholder comment:

```css
.selector {/* comment 1 */
    color: white; /* comment 2 */
}
```

**Comment by ben-eb** [comment]
Looks like an issue with resetting `decl.between`. Thanks for reporting.

**Comment by ben-eb** [comment]
Released as `1.2.1`.

**Comment by Mottie** [comment]
Thanks for the fix!

**Comment by Mottie** [comment]
Still one minor issue though. If I include a comment before the selectors, it adds an extra carriage return now:

Starting with:

```css
/* comment 0 */
.selector {
  /* comment 1 */
  color: /*[[placeholder]]*/ white;
  /* comment 2 */
}
```

the result becomes:

```css
/* comment 0 */

.selector {/* comment 1 */
    color: /*[[placeholder]]*/ white; /* comment 2 */
}
```

Any way to get the first comment directly above the selector, and the second comment back on it's own line? :grin:

**Comment by ben-eb** [comment]
This might need a bit more thought. For example if we have some CSS like this:

```css
h1 {
  color: black; /* Don't change this line! */
}
```

The formatter would then break the semantics of the comment. I wonder if there is some way to tell if both the property value pair & the comment are on the same line.



https://github.com/ben-eb/perfectionist/issues/4
