### ISSUE TITLE
One selector per line?

### ISSUE THREAD

**Issue by ghost** [ben-eb/perfectionist#86]
I'm looking to have output like this:
```css
foo,
bar,
baz { qux: quux; }
```

However, all three `format` options seem to leave the selectors on one line.  Is this possible?
